FROM gradle:8.14.3-jdk21 AS build
WORKDIR /workspace
COPY . .
RUN ./gradlew :server:buildFatJar --no-daemon

FROM eclipse-temurin:21-jre
EXPOSE 8080
WORKDIR /app
COPY --from=build /workspace/server/build/libs/fat.jar /app/app.jar
COPY --from=build /workspace/generate_csv.sh /app/generate_csv.sh
RUN chmod +x /app/generate_csv.sh
ENTRYPOINT ["java","-jar","/app/app.jar"]
