services:
  api:
    build:
      context: ..
      dockerfile: server/Dockerfile.api
    ports:
      - "${API_HOST_PORT:-8080}:8080"
    env_file:
      - .env
    environment:
      - APP_ROLE=api
      - SERVER_PORT=8080
      - PRICE_TAG_PARSER_SCRIPT=/app/generate_csv.sh
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./files:/app/files
    runtime: nvidia
    restart: always
