# syntax=docker/dockerfile:1.7

FROM gradle:8.14.3-jdk21 AS build
WORKDIR /workspace

COPY --chown=gradle:gradle gradlew gradlew.bat settings.gradle.kts build.gradle.kts gradle.properties ./
COPY --chown=gradle:gradle gradle ./gradle
COPY --chown=gradle:gradle composeApp/build.gradle.kts ./composeApp/build.gradle.kts
COPY --chown=gradle:gradle server/build.gradle.kts ./server/build.gradle.kts
COPY --chown=gradle:gradle shared/build.gradle.kts ./shared/build.gradle.kts

RUN --mount=type=cache,id=pricetagparser-gradle-cache,target=/home/gradle/.gradle,uid=1000,gid=1000,sharing=locked \
    ./gradlew :server:buildFatJar :composeApp:wasmJsBrowserDistribution --no-daemon --parallel --dry-run

COPY --chown=gradle:gradle composeApp/src ./composeApp/src
COPY --chown=gradle:gradle server/src ./server/src
COPY --chown=gradle:gradle shared/src ./shared/src

RUN --mount=type=cache,id=pricetagparser-gradle-cache,target=/home/gradle/.gradle,uid=1000,gid=1000,sharing=locked \
    ./gradlew :server:buildFatJar :composeApp:wasmJsBrowserDistribution --no-daemon --parallel

FROM eclipse-temurin:21-jre
EXPOSE 8080
WORKDIR /app
COPY --from=build /workspace/server/build/libs/fat.jar /app/app.jar
COPY --from=build /workspace/composeApp/build/dist/wasmJs/productionExecutable /app/web
ENTRYPOINT ["java","-jar","/app/app.jar"]
