FROM gradle:8.14.3-jdk21 AS build
WORKDIR /workspace
COPY . .
RUN ./gradlew :composeApp:composeCompatibilityBrowserDistribution --no-daemon

FROM busybox:1.37
WORKDIR /www
COPY --from=build /workspace/composeApp/build/dist/composeWebCompatibility/productionExecutable /www
EXPOSE 80
CMD ["httpd", "-f", "-p", "80", "-h", "/www"]
