FROM gradle:8.14.3-jdk21 AS build
WORKDIR /workspace
COPY . .
RUN ./gradlew :composeApp:composeCompatibilityBrowserDistribution --no-daemon

FROM eclipse-temurin:21-jre
EXPOSE 8080
WORKDIR /app
COPY --from=build /workspace/composeApp/build/dist/composeWebCompatibility/productionExecutable /app/web
RUN chmod +x /app/generate_csv.sh
